version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.dokka:dokka-maven-plugin
    versions:
    - 1.4.20
    - 1.4.20-dev-65
    - 1.4.30
  - dependency-name: io.ktor:ktor-server-core
    versions:
    - 1.5.1
    - 1.5.2
